[package]
name = "app"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "gpui_demo"
path = "src/main.rs"

[dependencies]
ui.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
gpui_tokio.workspace = true
base-gpui.workspace = true
gpui-wry.workspace = true
raw-window-handle.workspace = true
wry.workspace = true

anyhow.workspace = true
reqwest.workspace = true
rio-vt.workspace = true
rust-embed.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[target."cfg(target_os = \"linux\")".dependencies]
gtk = "0.18.2"

[target.'cfg(target_family = "wasm")'.dependencies]
web-sys = { version = "0.3", features = ["Window", "Location"] }
wasm-bindgen = "=0.2.120"
