use gpui::{AnyElement, IntoElement};
use ui::components::button;

pub struct DemoEntry {
    pub slug: &'static str,
    pub title: &'static str,
    /// Demos return their concrete element type; the registry erases it here
    /// so every entry fits one table (a fn pointer must name a single return
    /// type, and `AnyElement` is gpui's type-erased element).
    pub render: fn() -> AnyElement,
}

// Slugs are hyphenated to match the docs page URLs generated by
// scripts/build-site.mjs (`alert_dialog.md` -> `/components/alert-dialog.html`).
pub fn all() -> &'static [DemoEntry] {
    &[DemoEntry {
        slug: "button",
        title: "Button",
        render: || button::render().into_any_element(),
    }]
}

pub fn find(slug: &str) -> Option<&'static DemoEntry> {
    all().iter().find(|entry| entry.slug == slug)
}
